import React from 'react'
import './style.css'
import { Table } from 'antd';
import TokenDefaultPic from '../../../assets/token-default.svg'


const Reports = () => {
    return (
        <>
            <div className=''>
                <div class="w-full flex items-center justify-between">
                    <div style={{ textAlign: "start" }}>
                        <h1 class="text-2xl text-zinc-200 font-bold">
                            Reports
                        </h1>
                        <p class="text-[12px] text-zinc-400 text-[400]">
                            Audit reports generated by community
                        </p>
                    </div>
                    <button class="bg-[#0E76FD] p-2 flex items-center justify-center gap-1">
                        <img style={{ color: "white" }} alt="report-icon" loading="lazy" width="16" height="16" decoding="async" data-nimg="1" src="https://app.aiaegis.org/icons/nav/reports.svg" id="style-sG8Nc" class="style-sG8Nc" />
                        <p class="text-[14px] md:text-[16px] font-[500] text-zinc-50">
                            Request Report
                        </p>
                    </button>
                </div>
            </div>
            {/* Reports */}
            <div style={{width:"125.2%", marginTop: "40px"}}>
                <div class="w-[90%] md:w-[80%] flex flex-col gap-8 snipcss-27GRD">
                    <div class="relative w-full overflow-auto">
                        <table class="w-full caption-bottom text-sm">
                            <thead class="[&amp;_tr]:border-b bg-[#0D0D0D]">
                                <tr class="border-b transition-colors hover:bg-zinc-100/50 data-[state=selected]:bg-zinc-100 dark:hover:bg-zinc-800/50 dark:data-[state=selected]:bg-zinc-800">
                                    <th class="h-12 px-4 text-left align-middle font-medium text-zinc-500 [&amp;:has([role=checkbox])]:pr-0 dark:text-zinc-400">
                                    </th>
                                    <th class="h-12 px-4 text-left align-middle font-medium text-zinc-500 [&amp;:has([role=checkbox])]:pr-0 dark:text-zinc-400">
                                        TOKENS
                                    </th>
                                    <th class="h-12 px-4 text-left align-middle font-medium text-zinc-500 [&amp;:has([role=checkbox])]:pr-0 dark:text-zinc-400">
                                        CA
                                    </th>
                                    <th class="h-12 px-4 text-left align-middle font-medium text-zinc-500 [&amp;:has([role=checkbox])]:pr-0 dark:text-zinc-400">
                                        AUDITED DATE
                                    </th>
                                    <th class="h-12 px-4 text-left align-middle font-medium text-zinc-500 [&amp;:has([role=checkbox])]:pr-0 dark:text-zinc-400">
                                        FINDINGS
                                    </th>
                                </tr>
                            </thead>
                            <tbody class="[&amp;_tr:last-child]:border-0 bg-[#151515]">
                                <tr class="transition-colors hover:bg-zinc-100/50 data-[state=selected]:bg-zinc-100 dark:hover:bg-zinc-800/50 dark:data-[state=selected]:bg-zinc-800 border-b border-[#262626]">
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <img alt="ASG" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-full" src="https://app.aiaegis.org/_next/image?url=%2Fapi%2Ftoken%2Fimage%3Fq%3Dasg.png%3F1698895535&amp;w=64&amp;q=75"/>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 text-[12px] font-[400] text-zinc-100">
                                        ASG
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 flex items-center gap-1">
                                        <p class="text-[12px] text-blue-400 uppercase">
                                            0xb53368...a1F7a
                                        </p>
                                        <button type="button">
                                            <img alt="copy" loading="lazy" width="12" height="12" decoding="async" data-nimg="1" src="https://app.aiaegis.org/icons/copy.svg" id="style-DY4gL" class="style-DY4gL" />
                                        </button>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <div class="flex items-center gap-2">
                                            <p class="text-zinc-200 text-[12px] font-[400]">
                                                02-02-24
                                            </p>
                                            <p class="text-zinc-200 text-[12px] font-[400] uppercase">
                                                5:03 AM
                                            </p>
                                        </div>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <button data-state="closed" class="w-full">
                                            <div class="w-full min-w-[300px] h-[20px] flex items-center">
                                                <div class="h-[20px] bg-[#353535] style-WI1X5" id="style-WI1X5">
                                                </div>
                                                <div class="h-[20px] bg-[#0096B7] style-avYiA" id="style-avYiA">
                                                </div>
                                                <div class="h-[20px] bg-[#D49900] style-rjoro" id="style-rjoro">
                                                </div>
                                            </div>
                                        </button>
                                    </td>
                                </tr>
                                <tr class="transition-colors hover:bg-zinc-100/50 data-[state=selected]:bg-zinc-100 dark:hover:bg-zinc-800/50 dark:data-[state=selected]:bg-zinc-800 border-b border-[#262626]">
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <img alt="ZCX" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-full" src="https://app.aiaegis.org/_next/image?url=%2Fapi%2Ftoken%2Fimage%3Fq%3Dlogo128px.png%3F1700169101&amp;w=64&amp;q=75"/>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 text-[12px] font-[400] text-zinc-100">
                                        ZCX
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 flex items-center gap-1">
                                        <p class="text-[12px] text-blue-400 uppercase">
                                            0xc52c32...28804
                                        </p>
                                        <button type="button">
                                            <img alt="copy" loading="lazy" width="12" height="12" decoding="async" data-nimg="1" src="https://app.aiaegis.org/icons/copy.svg" id="style-LGbcc" class="style-LGbcc" />
                                        </button>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <div class="flex items-center gap-2">
                                            <p class="text-zinc-200 text-[12px] font-[400]">
                                                02-02-24
                                            </p>
                                            <p class="text-zinc-200 text-[12px] font-[400] uppercase">
                                                11:55 AM
                                            </p>
                                        </div>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <button data-state="closed" class="w-full">
                                            <div class="w-full min-w-[300px] h-[20px] flex items-center">
                                                <div class="h-[20px] bg-[#353535] style-MEAOj" id="style-MEAOj">
                                                </div>
                                                <div class="h-[20px] bg-[#0096B7] style-KPsVK" id="style-KPsVK">
                                                </div>
                                                <div class="h-[20px] bg-[#D49900] style-nKqtX" id="style-nKqtX">
                                                </div>
                                            </div>
                                        </button>
                                    </td>
                                </tr>
                                <tr class="transition-colors hover:bg-zinc-100/50 data-[state=selected]:bg-zinc-100 dark:hover:bg-zinc-800/50 dark:data-[state=selected]:bg-zinc-800 border-b border-[#262626]">
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <img alt="MAG" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-full" src="https://app.aiaegis.org/_next/image?url=%2Fapi%2Ftoken%2Fimage%3Fq%3D20231213_112204.jpg%3F1702499402&amp;w=64&amp;q=75"/>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 text-[12px] font-[400] text-zinc-100">
                                        MAG
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 flex items-center gap-1">
                                        <p class="text-[12px] text-blue-400 uppercase">
                                            0xb9d4B6...B35ed
                                        </p>
                                        <button type="button">
                                            <img alt="copy" loading="lazy" width="12" height="12" decoding="async" data-nimg="1" src="https://app.aiaegis.org/icons/copy.svg" id="style-r6mjy" class="style-r6mjy" />
                                        </button>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <div class="flex items-center gap-2">
                                            <p class="text-zinc-200 text-[12px] font-[400]">
                                                02-02-24
                                            </p>
                                            <p class="text-zinc-200 text-[12px] font-[400] uppercase">
                                                3:09 PM
                                            </p>
                                        </div>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <button data-state="closed" class="w-full">
                                            <div class="w-full min-w-[300px] h-[20px] flex items-center">
                                                <div class="h-[20px] bg-[#353535] style-GlS8M" id="style-GlS8M">
                                                </div>
                                                <div class="h-[20px] bg-[#0096B7] style-6nK47" id="style-6nK47">
                                                </div>
                                                <div class="h-[20px] bg-[#D49900] style-G8x9F" id="style-G8x9F">
                                                </div>
                                            </div>
                                        </button>
                                    </td>
                                </tr>
                                <tr class="transition-colors hover:bg-zinc-100/50 data-[state=selected]:bg-zinc-100 dark:hover:bg-zinc-800/50 dark:data-[state=selected]:bg-zinc-800 border-b border-[#262626]">
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <img alt="AEGIS" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-full" src="https://app.aiaegis.org/_next/image?url=%2Fapi%2Ftoken%2Fimage%3Fq%3DUXDa3TDq_400x400.jpg%3F1700909114&amp;w=64&amp;q=75"/>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 text-[12px] font-[400] text-zinc-100">
                                        AEGIS
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 flex items-center gap-1">
                                        <p class="text-[12px] text-blue-400 uppercase">
                                            0x55a8f6...e19f4
                                        </p>
                                        <button type="button">
                                            <img alt="copy" loading="lazy" width="12" height="12" decoding="async" data-nimg="1" src="https://app.aiaegis.org/icons/copy.svg" id="style-77441" class="style-77441" />
                                        </button>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <div class="flex items-center gap-2">
                                            <p class="text-zinc-200 text-[12px] font-[400]">
                                                02-02-24
                                            </p>
                                            <p class="text-zinc-200 text-[12px] font-[400] uppercase">
                                                6:33 PM
                                            </p>
                                        </div>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <button data-state="closed" class="w-full">
                                            <div class="w-full min-w-[300px] h-[20px] flex items-center">
                                                <div class="h-[20px] bg-[#353535] style-fX6j7" id="style-fX6j7">
                                                </div>
                                                <div class="h-[20px] bg-[#0096B7] style-hRxOQ" id="style-hRxOQ">
                                                </div>
                                                <div class="h-[20px] bg-[#D49900] style-BFjlN" id="style-BFjlN">
                                                </div>
                                            </div>
                                        </button>
                                    </td>
                                </tr>
                                <tr class="transition-colors hover:bg-zinc-100/50 data-[state=selected]:bg-zinc-100 dark:hover:bg-zinc-800/50 dark:data-[state=selected]:bg-zinc-800 border-b border-[#262626]">
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <img alt="imgnAI" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-full" src="https://app.aiaegis.org/_next/image?url=%2Fapi%2Ftoken%2Fimage%3Fq%3Dimgnai-200x200.png%3F1698476572&amp;w=64&amp;q=75"/>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 text-[12px] font-[400] text-zinc-100">
                                        imgnAI
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 flex items-center gap-1">
                                        <p class="text-[12px] text-blue-400 uppercase">
                                            0xA735A3...6CBe0
                                        </p>
                                        <button type="button">
                                            <img alt="copy" loading="lazy" width="12" height="12" decoding="async" data-nimg="1" src="https://app.aiaegis.org/icons/copy.svg" id="style-nRTwD" class="style-nRTwD" />
                                        </button>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <div class="flex items-center gap-2">
                                            <p class="text-zinc-200 text-[12px] font-[400]">
                                                02-02-24
                                            </p>
                                            <p class="text-zinc-200 text-[12px] font-[400] uppercase">
                                                6:56 PM
                                            </p>
                                        </div>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <button data-state="closed" class="w-full">
                                            <div class="w-full min-w-[300px] h-[20px] flex items-center">
                                                <div class="h-[20px] bg-[#353535] style-nmdGF" id="style-nmdGF">
                                                </div>
                                                <div class="h-[20px] bg-[#0096B7] style-ojd6k" id="style-ojd6k">
                                                </div>
                                                <div class="h-[20px] bg-[#D49900] style-D6EEj" id="style-D6EEj">
                                                </div>
                                            </div>
                                        </button>
                                    </td>
                                </tr>
                                <tr class="transition-colors hover:bg-zinc-100/50 data-[state=selected]:bg-zinc-100 dark:hover:bg-zinc-800/50 dark:data-[state=selected]:bg-zinc-800 border-b border-[#262626]">
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <img alt="RBX" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-full style-UyOph" src={TokenDefaultPic} id="style-UyOph" />
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 text-[12px] font-[400] text-zinc-100">
                                        RBX
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 flex items-center gap-1">
                                        <p class="text-[12px] text-blue-400 uppercase">
                                            0x3ba925...7309e
                                        </p>
                                        <button type="button">
                                            <img alt="copy" loading="lazy" width="12" height="12" decoding="async" data-nimg="1" src="https://app.aiaegis.org/icons/copy.svg" id="style-I1d9W" class="style-I1d9W" />
                                        </button>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <div class="flex items-center gap-2">
                                            <p class="text-zinc-200 text-[12px] font-[400]">
                                                29-01-24
                                            </p>
                                            <p class="text-zinc-200 text-[12px] font-[400] uppercase">
                                                7:59 PM
                                            </p>
                                        </div>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <button data-state="closed" class="w-full">
                                            <div class="w-full min-w-[300px] h-[20px] flex items-center">
                                                <div class="h-[20px] bg-[#353535] style-LB74g" id="style-LB74g">
                                                </div>
                                                <div class="h-[20px] bg-[#0096B7] style-HHjro" id="style-HHjro">
                                                </div>
                                                <div class="h-[20px] bg-[#D49900] style-bDEbd" id="style-bDEbd">
                                                </div>
                                            </div>
                                        </button>
                                    </td>
                                </tr>
                                <tr class="transition-colors hover:bg-zinc-100/50 data-[state=selected]:bg-zinc-100 dark:hover:bg-zinc-800/50 dark:data-[state=selected]:bg-zinc-800 border-b border-[#262626]">
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <img alt="RLB" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-full style-KXB6J" src={TokenDefaultPic} id="style-KXB6J" />
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 text-[12px] font-[400] text-zinc-100">
                                        RLB
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 flex items-center gap-1">
                                        <p class="text-[12px] text-blue-400 uppercase">
                                            0x046EeE...e3f3d
                                        </p>
                                        <button type="button">
                                            <img alt="copy" loading="lazy" width="12" height="12" decoding="async" data-nimg="1" src="https://app.aiaegis.org/icons/copy.svg" id="style-ZTUJY" class="style-ZTUJY" />
                                        </button>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <div class="flex items-center gap-2">
                                            <p class="text-zinc-200 text-[12px] font-[400]">
                                                30-01-24
                                            </p>
                                            <p class="text-zinc-200 text-[12px] font-[400] uppercase">
                                                3:10 AM
                                            </p>
                                        </div>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <button data-state="closed" class="w-full">
                                            <div class="w-full min-w-[300px] h-[20px] flex items-center">
                                                <div class="h-[20px] bg-[#353535] style-SCor3" id="style-SCor3">
                                                </div>
                                                <div class="h-[20px] bg-[#0096B7] style-eWjKs" id="style-eWjKs">
                                                </div>
                                                <div class="h-[20px] bg-[#D49900] style-LJkZi" id="style-LJkZi">
                                                </div>
                                            </div>
                                        </button>
                                    </td>
                                </tr>
                                <tr class="transition-colors hover:bg-zinc-100/50 data-[state=selected]:bg-zinc-100 dark:hover:bg-zinc-800/50 dark:data-[state=selected]:bg-zinc-800 border-b border-[#262626]">
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <img alt="PABLO" loading="lazy" width="28" height="28" decoding="async" data-nimg="1" class="rounded-full" src="https://app.aiaegis.org/_next/image?url=%2Fapi%2Ftoken%2Fimage%3Fq%3DFSNlYKG.png%3F1706074430&amp;w=64&amp;q=75"/>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 text-[12px] font-[400] text-zinc-100">
                                        PABLO
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0 flex items-center gap-1">
                                        <p class="text-[12px] text-blue-400 uppercase">
                                            0x926FF6...71F47
                                        </p>
                                        <button type="button">
                                            <img alt="copy" loading="lazy" width="12" height="12" decoding="async" data-nimg="1" src="https://app.aiaegis.org/icons/copy.svg" id="style-m6DVU" class="style-m6DVU" />
                                        </button>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <div class="flex items-center gap-2">
                                            <p class="text-zinc-200 text-[12px] font-[400]">
                                                02-02-24
                                            </p>
                                            <p class="text-zinc-200 text-[12px] font-[400] uppercase">
                                                8:40 PM
                                            </p>
                                        </div>
                                    </td>
                                    <td class="p-4 align-middle [&amp;:has([role=checkbox])]:pr-0">
                                        <button data-state="closed" class="w-full">
                                            <div class="w-full min-w-[300px] h-[20px] flex items-center">
                                                <div class="h-[20px] bg-[#353535] style-6WoW5" id="style-6WoW5">
                                                </div>
                                                <div class="h-[20px] bg-[#0096B7] style-SqSBt" id="style-SqSBt">
                                                </div>
                                                <div class="h-[20px] bg-[#D49900] style-kZdF2" id="style-kZdF2">
                                                </div>
                                            </div>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
             {/* <Table
                dataSource={data}
                columns={columns}
                pagination={false} // Disable pagination for now
                className="mt-5 custom-table"
            /> */}
        </>
    )
}

export default Reports